services:
  weapon_strike_arena:
    build: .
    ports:
      - "8088:80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.weapon_strike_arena.rule=Host(`luke.chazmar.com`)"
      - "traefik.http.routers.weapon_strike_arena.entrypoints=websecure"
      - "traefik.http.routers.weapon_strike_arena.tls.certresolver=letsencrypt"

  